FROM bitnami/minideb

RUN apt-get update && apt-get -y install curl

RUN apt-get update && apt-get install nginx -y && service nginx start

EXPOSE 80/udp

WORKDIR "/var/www/html"

COPY exemple.html index.html

CMD ["nginx", "-g", "daemon off;"]
